import { motion } from 'framer-motion'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, Zap, Brain, Sparkles, TrendingUp } from 'lucide-react'
import { useAuthStore } from '../store/index'
import { FloatingParticles, GlowingGrid } from '../components/BackgroundEffects'
import { Button } from '../components/UIComponents.jsx'
import AIAssistant from '../components/AIAssistant'

const Home = () => {
  const { isAuthenticated } = useAuthStore()
  const navigate = useNavigate()

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Generation',
      description: 'Dynamic quizzes generated by advanced AI algorithms tailored to your learning level'
    },
    {
      icon: TrendingUp,
      title: 'Detailed Analytics',
      description: 'Track your progress with comprehensive statistics and performance insights'
    },
    {
      icon: Zap,
      title: 'Gamified Learning',
      description: 'Earn XP, unlock badges, and climb the leaderboard while learning'
    },
    {
      icon: Sparkles,
      title: 'Personalized Path',
      description: 'Get AI-powered recommendations based on your strengths and weaknesses'
    },
  ]

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  }

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        type: 'spring',
        stiffness: 100,
        damping: 10,
      },
    },
  }

  return (
    <div className="min-h-screen bg-gradient-cyber overflow-hidden">
      <FloatingParticles />
      <GlowingGrid />
      <AIAssistant />

      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass-lg border-b border-cyberpunk-blue/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <motion.div
              whileHover={{ scale: 1.1 }}
              className="text-2xl font-bold bg-gradient-to-r from-cyberpunk-blue to-cyberpunk-purple bg-clip-text text-transparent"
            >
              ⚡ TechQuiz AI
            </motion.div>
            <div className="flex items-center gap-4">
              {isAuthenticated ? (
                <Button onClick={() => navigate('/dashboard')} variant="primary">
                  Go to Dashboard
                  <ArrowRight size={18} />
                </Button>
              ) : (
                <>
                  <Link to="/login">
                    <Button variant="secondary">Login</Button>
                  </Link>
                  <Link to="/signup">
                    <Button variant="primary">Sign Up</Button>
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-16 px-4 relative z-10">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="max-w-4xl mx-auto text-center"
        >
          <motion.div variants={itemVariants} className="mb-6 relative z-10">
            <h1 className="hero-text-sharp text-5xl md:text-7xl font-bold mb-4 tracking-tight text-white drop-shadow-[0_16px_45px_rgba(0,0,0,0.18)]">
              <span className="bg-gradient-to-r from-cyberpunk-blue via-cyberpunk-purple to-cyberpunk-pink bg-clip-text text-transparent">
                Generate AI-Powered
              </span>
              <br />
              <span className="relative inline-flex items-center">
                <span className="relative z-10">Technology Quizzes Instantly</span>
                <span className="hero-glow-behind rounded-3xl bg-cyberpunk-blue/10" />
              </span>
            </h1>
          </motion.div>

          <motion.p
            variants={itemVariants}
            className="text-xl text-cyberpunk-text-secondary mb-8 max-w-2xl mx-auto leading-relaxed"
          >
            Master any technology with dynamic, AI-generated quizzes. Learn smarter, progress faster, and dominate the leaderboard.
          </motion.p>

          <motion.div
            variants={itemVariants}
            className="flex flex-col sm:flex-row gap-4 justify-center mb-16"
          >
            {isAuthenticated ? (
              <>
                <Button onClick={() => navigate('/dashboard')} variant="primary" size="lg">
                  Start Learning
                  <ArrowRight size={20} />
                </Button>
              </>
            ) : (
              <>
                <Link to="/signup">
                  <Button variant="primary" size="lg">
                    Start Learning Now
                    <ArrowRight size={20} />
                  </Button>
                </Link>
                <Link to="/login">
                  <Button variant="secondary" size="lg">
                    Already have an account?
                  </Button>
                </Link>
              </>
            )}
          </motion.div>

          {/* Stats */}
          <motion.div
            variants={itemVariants}
            className="grid grid-cols-3 gap-4 max-w-2xl mx-auto mb-16"
          >
            {[
              { label: 'Topics', value: '9+' },
              { label: 'Questions', value: '1000+' },
              { label: 'Users', value: '5K+' },
            ].map((stat, index) => (
              <div key={index} className="glass rounded-xl p-4">
                <p className="text-3xl font-bold bg-gradient-to-r from-cyberpunk-blue to-cyberpunk-purple bg-clip-text text-transparent">
                  {stat.value}
                </p>
                <p className="text-cyberpunk-text-secondary text-sm">{stat.label}</p>
              </div>
            ))}
          </motion.div>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 relative z-10">
        <div className="max-w-6xl mx-auto">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-4xl font-bold text-center mb-12 bg-gradient-to-r from-cyberpunk-blue to-cyberpunk-purple bg-clip-text text-transparent"
          >
            Why Choose TechQuiz AI?
          </motion.h2>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="grid md:grid-cols-2 gap-8"
          >
            {features.map((feature, index) => (
              <motion.div
                key={index}
                variants={itemVariants}
                className="glass rounded-xl p-8 hover:border-cyberpunk-blue/50 transition-all"
              >
                <motion.div
                  whileHover={{ scale: 1.1, rotate: 5 }}
                  className="text-4xl mb-4 text-cyberpunk-blue"
                >
                  <feature.icon size={32} />
                </motion.div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-cyberpunk-text-secondary">{feature.description}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-2xl mx-auto text-center"
        >
          <h2 className="text-4xl font-bold mb-6">Ready to Level Up Your Skills?</h2>
          <p className="text-xl text-cyberpunk-text-secondary mb-8">
            Join thousands of learners mastering technology with AI-powered quizzes.
          </p>
          {!isAuthenticated && (
            <Link to="/signup">
              <Button variant="primary" size="lg">
                Get Started Free
                <ArrowRight size={20} />
              </Button>
            </Link>
          )}
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-cyberpunk-blue/20 py-8 px-4 relative z-10">
        <div className="max-w-6xl mx-auto text-center text-cyberpunk-text-secondary text-sm">
          <p>&copy; 2024 TechQuiz AI. Built with ⚡ and AI magic.</p>
        </div>
      </footer>
    </div>
  )
}

export default Home
